# Generated by Django 4.2.7 on 2026-03-23 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        verbose_name="Аватар",
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, max_length=500, verbose_name="О себе"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="Публичный профиль"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль пользователя",
                "verbose_name_plural": "Профили пользователей",
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_games",
                    models.PositiveIntegerField(default=0, verbose_name="Всего игр"),
                ),
                (
                    "games_won",
                    models.PositiveIntegerField(default=0, verbose_name="Побед"),
                ),
                (
                    "games_lost",
                    models.PositiveIntegerField(default=0, verbose_name="Проигрышей"),
                ),
                (
                    "games_surrendered",
                    models.PositiveIntegerField(default=0, verbose_name="Сдался"),
                ),
                (
                    "games_archived",
                    models.PositiveIntegerField(default=0, verbose_name="Архив"),
                ),
                (
                    "best_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Лучшее время"
                    ),
                ),
                (
                    "best_score",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Лучший результат"
                    ),
                ),
                (
                    "current_level",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Текущий уровень"
                    ),
                ),
                (
                    "last_played",
                    models.DateTimeField(auto_now=True, verbose_name="Последняя игра"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="games.game",
                        verbose_name="Игра",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс пользователя",
                "verbose_name_plural": "Прогресс пользователей",
                "unique_together": {("user", "game")},
            },
        ),
    ]
