# Generated by Django 4.2.7 on 2026-04-02 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_userprogress_games_archived"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprogress",
            name="best_time",
        ),
    ]
