# Generated by Django 4.2.7 on 2026-04-02 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0003_remove_userprogress_best_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_games",
                    models.PositiveIntegerField(default=0, verbose_name="Всего игр"),
                ),
                (
                    "games_won",
                    models.PositiveIntegerField(default=0, verbose_name="Побед"),
                ),
                (
                    "games_lost",
                    models.PositiveIntegerField(default=0, verbose_name="Проигрышей"),
                ),
                (
                    "games_surrendered",
                    models.PositiveIntegerField(default=0, verbose_name="Сдался"),
                ),
                (
                    "best_score",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Лучший результат"
                    ),
                ),
                (
                    "total_play_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Общее время игры"
                    ),
                ),
                (
                    "last_played",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последняя игра"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статистика пользователя",
                "verbose_name_plural": "Статистика пользователей",
            },
        ),
    ]
