# Generated by Django 4.2.7 on 2026-04-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_userstatistics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userstatistics",
            name="best_score",
        ),
        migrations.RemoveField(
            model_name="userstatistics",
            name="last_played",
        ),
        migrations.RemoveField(
            model_name="userstatistics",
            name="total_play_time",
        ),
    ]
