# Generated by Django 4.2.7 on 2026-04-05 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_userstatistics_best_score_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprogress",
            name="best_score",
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="current_level",
        ),
    ]
