# Generated by Django 4.2.7 on 2026-04-05 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_userprogress_best_score_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userstatistics",
            name="user",
        ),
        migrations.DeleteModel(
            name="UserProgress",
        ),
        migrations.DeleteModel(
            name="UserStatistics",
        ),
    ]
