# Generated by Django 4.2.7 on 2026-04-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_userstatistics_user_delete_userprogress_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="bio",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="age",
            field=models.IntegerField(default=-1, verbose_name="Возраст"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="education",
            field=models.CharField(
                choices=[
                    ("not_specified", "Не указано"),
                    ("none", "Не имею образования (детский сад, дети 0+, до 6-7 лет)"),
                    (
                        "studying",
                        "Обучаюсь в настоящее время (школьники, студенты колледжей и вузов)",
                    ),
                    ("incomplete_secondary", "Неполное среднее (школа, 9 классов)"),
                    ("secondary", "Среднее общее (школа, 11 классов)"),
                    (
                        "vocational",
                        "Среднее профессиональное образование (колледж/ПТУ)",
                    ),
                    (
                        "higher",
                        "Высшее образование (бакалавриат/специалитет/магистратура)",
                    ),
                    (
                        "postgraduate",
                        "Послевузовское образование (аспирантура/ординатура/кандидат наук/доктор наук)",
                    ),
                ],
                default="not_specified",
                max_length=50,
                verbose_name="Образование",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                choices=[
                    ("unknown", "Неизвестно"),
                    ("male", "Мужской"),
                    ("female", "Женский"),
                ],
                default="unknown",
                max_length=20,
                verbose_name="Пол",
            ),
        ),
    ]
