# Generated by Django 4.2.7 on 2026-04-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_userprofile_bio_userprofile_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="age",
            field=models.IntegerField(
                blank=True, default=None, null=True, verbose_name="Возраст"
            ),
        ),
    ]
