# Generated by Django 4.2.7 on 2026-05-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_userprofile_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="show_hidden_games",
            field=models.BooleanField(
                default=True, verbose_name="Показывать выключенные игры"
            ),
        ),
    ]
