# Generated by Django 4.2.7 on 2026-05-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_userprofile_show_hidden_games"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="education",
            field=models.CharField(
                choices=[
                    ("not_specified", "Не указано"),
                    ("none", "Не имею образования (детский сад, дети 0+, до 6-7 лет)"),
                    (
                        "studying",
                        "Обучаюсь в настоящее время (школьники, студенты колледжей и вузов)",
                    ),
                    ("incomplete_secondary", "Неполное среднее (школа, 9 классов)"),
                    ("secondary", "Среднее общее (школа, 11 классов)"),
                    (
                        "vocational",
                        "Среднее профессиональное образование (колледж, ПТУ)",
                    ),
                    (
                        "higher",
                        "Высшее образование (бакалавриат, специалитет, магистратура)",
                    ),
                    (
                        "postgraduate",
                        "Послевузовское образование (аспирантура, ординатура, кандидат наук, доктор наук)",
                    ),
                ],
                default="not_specified",
                max_length=50,
                verbose_name="Образование",
            ),
        ),
    ]
