# Generated by Django 4.2.7 on 2026-05-26 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_userprofile_education"),
    ]

    operations = []
