# Generated by Django 4.2.7 on 2026-05-26 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_auto_20260526_2153"),
    ]

    operations = []
