# Generated by Django 4.2.7 on 2026-03-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="description",
            field=models.TextField(default="Описание игры Test Game"),
        ),
    ]
