# Generated by Django 4.2.7 on 2026-03-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_game_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="description",
            field=models.TextField(default="Описание игры по умолчанию"),
        ),
    ]
