# Generated by Django 4.2.7 on 2026-03-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_alter_game_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="short_description",
            field=models.TextField(default="Краткое описание игры по умолчанию"),
        ),
    ]
