# Generated by Django 4.2.7 on 2026-04-01 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_game_short_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"verbose_name": "Игра", "verbose_name_plural": "Игры"},
        ),
        migrations.AlterModelOptions(
            name="gamesession",
            options={
                "verbose_name": "Игровая сессия",
                "verbose_name_plural": "Игровые сессии",
            },
        ),
    ]
