# Generated by Django 4.2.7 on 2026-04-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_alter_game_options_alter_gamesession_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="avatar",
            field=models.CharField(
                default="media/avatars_games/game_base.png", max_length=255
            ),
        ),
    ]
