# Generated by Django 4.2.7 on 2026-04-02 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_game_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesession",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
