# Generated by Django 4.2.7 on 2026-04-02 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0007_alter_gamesession_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesession",
            name="finished_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
