# Generated by Django 4.2.7 on 2026-04-05 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0008_alter_gamesession_finished_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gamesession",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Игровая сессия",
                "verbose_name_plural": "Игровые сессии",
            },
        ),
        migrations.AlterField(
            model_name="gamesession",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="games.game",
            ),
        ),
        migrations.AlterField(
            model_name="gamesession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
